### ISSUE TITLE
[BE] 내가 구현해야하는 API 정리

### ISSUE THREAD

**Issue by Yejikwon** [Yejikwon/IssueTracker-08#3]
[이슈]
#22 목록 조회: 로그인한 사용자와 관련있는 issue를 모두 반환하는 API를 개발
- [x] 전체 이슈 조회
- [x] 세부 이슈 조회
<br/>

#25 issue open 여부 변경
- [x] 사용자가 체크박스로 선택한 issue list의 open 여부를 일괄 업데이트하는 API를 개발
   - 여러 개를 동시에 open 하도록 map 형태로 req.body를 받아버리면,
      만약 일부는 open 성공하고, 일부는 open 실패했을 때 결과를 리턴하기 애매함
   - 원래는 한 요청 당 한 query를 수행하는 게 맞으므로 이 이슈는 42번 이슈에서 생성한 API를 사용하면 될 듯하다.
   - <b>결론: open Issue를 여러번 돌리면 될 듯! (42번 이슈로 대체 가능해보여서 추가로 구현 X)</b>
<br/>

#42 이슈 클로즈 및 오픈: 
- [x] 클로즈하면 0(false) - 이슈 삭제의 느낌이 close
- [x] 오픈하면 1(true)로 바꿔주기
<br/>

#39 Issues 저장(생성)
- [x] 이슈 생성

- [ ] #30 이미지 저장이랑 연관되어 있음
<br/>

#40 이슈 수정
- [x]  이슈 내용 업데이트 요청
<br/>

#43 Assignee 수정
- [x] 이슈 담당자 생성
- [x] 이슈 담당자 삭제
<br/>

#44 Labels 수정
- [x] 이슈 라벨 생성
- [x] 이슈 라벨 삭제
<br/>

#45 Milestone 수정
- [x] 이슈 마일스톤 생성
- [x] 이슈 마일스톤 삭제
<br/>

#41 코멘트 생성 요청 (상세 이슈 보기 클릭 시 필요)
- [x] 이슈에 댓글 달면, 그에 맞는 코멘트 생성
<br/>

#46 이슈의 코멘트 개수 반환
- [x] 이슈의 코멘트 개수 반환
<br/>

#91 이슈의 코멘트 조회/수정/삭제
- [x] 이슈의 코멘트 조회/수정/삭제
<br/>

#75 Author을 조회하는 API
- [ ] 이슈 생성한 사람 조회 (선택된 사람이 만든 이슈만 보이도록)
<br/>

#76 Assignee을 조회하는 API 
- [x] 특정 Assignee 이슈만 조회 (이슈에 할당된 사람의 이슈만 보이도록)
<br/>

[로그인]
#19 로그인 중복체크
- [x] 로그인 중복체크 - 필요 없음!!!!!!!!
<br/>

[다같이]
27 필터링 이슈 데이터 반환
28 추가 필터링 이슈 데이터 반환
29 프로필 이미지 조회
30 이미지 저장

**Comment by Yejikwon** [comment]
tinyInt -> 1이 true

**Comment by Yejikwon** [comment]
### ios 부서에서 요청해주신 형식
~~~JSON
  {
    "issueId": 1,
    "username": "lala", 
    "userEmail": "lala@github.io",
    "title": "view create",
    "content": "",
    "isOpen": true,
    "milestone": "IOS",
    "label": ["IOS", "Swift"],
    "assign": ["why"],
    "createAt": "2020-10-28T10:01:49.000Z",
    "closeAt": "2020-10-28T10:01:49.000Z"
}
~~~

<br/>

### 내가 만든 API return 형식
~~~JSON
{
    "status": "success",
    "data": [
        {
            "issueId": 1,
            "email": "test@github.com",
            "name": "test",
            "milestone": "FE",
            "title": "ViewCreate",
            "content": "we develop",
            "isOpen": 1,
            "createAt": "2020-01-02T15:00:00.000Z",
            "closeAt": "2020-01-02T15:00:00.000Z",
            "label": [
                {
                    "labelName": "web",
                    "labelColor": "#121212",
                    "labelDescription": "fighting"
                },
                {
                    "labelName": "FE",
                    "labelColor": "#243412",
                    "labelDescription": "fighting"
                }
            ],
            "assign": [
                "test",
                "reality"
            ]
        },
    ]
}
~~~
